name: Build and Release Python Wheel

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload-wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update pyproject.toml version
        run: |
          # Update version in pyproject.toml to match the tag
          sed -i "s/^version = .*/version = \"${{ steps.get_version.outputs.version }}\"/" pyproject.toml
          
          # Verify the change
          grep "^version" pyproject.toml

      - name: Build wheel with uv
        run: |
          uv build --wheel

      - name: Upload wheel to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
