name: Build and Release Python Wheel

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload-wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Update package version from tag
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG_NAME#v}"
          echo "Setting version to: $VERSION"
          # Validate that VERSION is not empty and matches semantic versioning pattern
          if [[ -z "$VERSION" ]]; then
            echo "Error: VERSION is empty after extraction from tag: $TAG_NAME"
            exit 1
          fi
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?(\+[a-zA-Z0-9.-]+)?$ ]]; then
            echo "Warning: VERSION '$VERSION' does not match semantic versioning pattern, but proceeding anyway"
          fi
          uv version "$VERSION"

      - name: Build wheel with uv
        run: |
          uv build --wheel

      - name: Upload wheel to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
