# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI with lint, pytest and great expectation

on:
  workflow_dispatch:
  push:
    branches: none
  pull_request:
    branches: [ "main", "test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v1

    - name: Install project dependencies with uv
      run: uv sync # Use uv sync to install dependencies from pyproject.toml

    - name: Add lint/test tools with uv
      run: |
        uv add yapf flake8 pytest great_expectations

    - name: Automatic Formatting
      run: |
        # run yapf to format the scripts automatically
        uv run yapf -i --style '{use_tabs: False}' ./BasketIntelligence/create_season.py
        uv run yapf -i --style '{use_tabs: False}' ./BasketIntelligence/load_season_data.py
        uv run yapf -i ./setup.py
        uv run yapf -i --style '{use_tabs=False}' ./tests/pyTest/test_create_season.py
        uv run yapf -i --style '{use_tabs=False}' ./tests/data_quality_test/run_great_expectations.py
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 . --count --select=E9,F63,F7,F82,E111 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: run pytest
      run: |
        uv run pytest tests/pyTest/

    - name: run data quality test (great expectations)
      run: |
        uv run tests/data_quality_test/run_great_expectations.py
